name: Black Linter

on:
  pull_request:
    branches:
      - main  # Replace with your default branch
  push:
    branches:
      - main  # Replace with your default branch

jobs:
  lint:
    name: Run Black
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # You can specify the version you need

      - name: Install dependencies
        run: pip install black

      - name: Run Black
        run: black .  # Replace "." with the path to your Python files or directories
