name: CI for X17-Surface

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Dummy step to test the workflow
      - name: Print a message
        run: echo "Hello, world!"

      # One more dummy step to test the workflow
      - name: Print another message
        run: echo "The workflow is working!"

      # Run tests (to be implemented)
